apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: prasanna@123
            - name: MYSQL_DATABASE
              value: user
            
          ports:
            - containerPort: 3306
            
            
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
    
spec:
  selector:
    app: mysql
    tire: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

